// Único punto de acceso al estado global de la plataforma.
// El store, el apiSlice (RTK Query) y el authSlice llegan por Module Federation
// desde mf-shared, así que existe UNA sola instancia en runtime compartida por
// el shell y todos los microfrontends.
// Los alias de vite/tsconfig redirigen "@/store/store", "@/slices/*" y
// "@/services/baseQuery" a este archivo: por eso las páginas no cambiaron.
// Se re-exporta nombre por nombre a propósito: el plugin de federación no
// puede resolver `export * from` (no conoce los nombres en build time).
import {
  store,
  apiSlice,
  authReducer,
  setCredentials,
  logout,
  baseQuery,
  baseQueryWithReauth,
  useRegisterCreatorMutation,
  useRegisterDonorMutation,
  useLoginUserMutation,
  useRefreshTokenMutation,
  useGetMyProfileQuery,
  useUpdateMyProfileMutation,
  useListCampaignsQuery,
  useGetCampaignQuery,
  useCreateCampaignMutation,
  useEditCampaignMutation,
  useAddCampaignUpdateMutation,
  useAddCampaignCommentMutation,
  useInteractCampaignMutation,
  useCampaignInterestedQuery,
  useDonateMutation,
  useConfirmPaymentMutation,
  useIncomingPendingQuery,
  useConfirmIncomingMutation,
  useMyDonationsQuery,
  useMyInteractionsQuery,
  useMyNotificationsQuery,
  useMarkNotificationsReadMutation,
  usePersonalizedFeedQuery,
  useTrendingQuery,
  useRecordViewMutation,
  useAdminUsersQuery,
  useAdminUserDetailQuery,
  useAdminCreateUserMutation,
  useAdminUpdateUserMutation,
  useAdminDeleteUserMutation,
  useAdminCampaignsQuery,
  useAdminCampaignDetailQuery,
  useAdminUpdateCampaignMutation,
  useAdminDeleteCampaignMutation,
  useAdminPendingDonationsQuery,
  useAdminConfirmDonationMutation,
} from "mf_shared/state";

export type * from "mf_shared/state";

export {
  store,
  apiSlice,
  authReducer,
  setCredentials,
  logout,
  baseQuery,
  baseQueryWithReauth,
  useRegisterCreatorMutation,
  useRegisterDonorMutation,
  useLoginUserMutation,
  useRefreshTokenMutation,
  useGetMyProfileQuery,
  useUpdateMyProfileMutation,
  useListCampaignsQuery,
  useGetCampaignQuery,
  useCreateCampaignMutation,
  useEditCampaignMutation,
  useAddCampaignUpdateMutation,
  useAddCampaignCommentMutation,
  useInteractCampaignMutation,
  useCampaignInterestedQuery,
  useDonateMutation,
  useConfirmPaymentMutation,
  useIncomingPendingQuery,
  useConfirmIncomingMutation,
  useMyDonationsQuery,
  useMyInteractionsQuery,
  useMyNotificationsQuery,
  useMarkNotificationsReadMutation,
  usePersonalizedFeedQuery,
  useTrendingQuery,
  useRecordViewMutation,
  useAdminUsersQuery,
  useAdminUserDetailQuery,
  useAdminCreateUserMutation,
  useAdminUpdateUserMutation,
  useAdminDeleteUserMutation,
  useAdminCampaignsQuery,
  useAdminCampaignDetailQuery,
  useAdminUpdateCampaignMutation,
  useAdminDeleteCampaignMutation,
  useAdminPendingDonationsQuery,
  useAdminConfirmDonationMutation,
};
